-- Reset controlado para limpar dados de teste da fundacao.
-- NAO executa referencias Pepper. Mantem estrutura e zera apenas dados operacionais/teste.
-- Uso recomendado: somente depois de confirmar que o ambiente contem dados descartaveis.

begin;

truncate table
  "InvoiceStatusHistory",
  "InvoiceItem",
  "Invoice",
  "ShipmentStatusHistory",
  "ShipmentPackage",
  "Shipment",
  "ShipmentGrouping",
  "PickingSeparationStatusHistory",
  "PickingSeparationItem",
  "PickingSeparation",
  "FoundationPriceListItem",
  "FoundationPriceList",
  "FoundationStockMovement",
  "CatalogVariantAccountState",
  "FoundationAsset",
  "FoundationInboundEvent",
  "SupplierFinancialStatusHistory",
  "SupplierFinancialAttachment",
  "SupplierFinancialEntry",
  "SupplierOrderWorkflowHistory",
  "SupplierOrderStatusHistory",
  "SupplierOrderAttachment",
  "SupplierOrderItem",
  "SupplierOrder",
  "ReplenishmentRequestItem",
  "ReplenishmentRequest",
  "CatalogOnboardingItem",
  "ProductSuggestionStatusHistory",
  "ProductSuggestionColor",
  "ProductSuggestionSize",
  "ProductSuggestionImage",
  "ProductSuggestion",
  "SuggestionValidationDraft",
  "PepperIaMessage",
  "PepperIaThread",
  "MessageAttachment",
  "Message",
  "Conversation",
  "AuditLog",
  "SupplierSalesMetricDaily",
  "ProductSalesMetricDaily",
  "VariantSalesMetricDaily",
  "SalesOrderStatusHistory",
  "SalesOrderItem",
  "SalesOrder",
  "SyncRun",
  "TinyWebhookLog",
  "TinyImportItem",
  "TinyImportBatch",
  "CatalogProductSupplier",
  "CatalogTinyMapping",
  "CatalogAttribute",
  "CatalogImage",
  "CatalogPrice",
  "CatalogInventory",
  "CatalogVariant",
  "CatalogProduct",
  "InventorySnapshot",
  "ProductSupplier",
  "Product",
  "FoundationContact",
  "Customer"
restart identity cascade;

commit;
