export type PepperReferenceItem = {
  code: string;
  label: string;
  sortOrder: number;
};

export const PEPPER_SIZE_REFERENCES: PepperReferenceItem[] = [
  { code: "01", label: "1 ano", sortOrder: 10 },
  { code: "02", label: "2 anos", sortOrder: 20 },
  { code: "03", label: "3 anos", sortOrder: 30 },
  { code: "04", label: "4 anos", sortOrder: 40 },
  { code: "06", label: "6 anos", sortOrder: 50 },
  { code: "08", label: "8 anos", sortOrder: 60 },
  { code: "10", label: "10 anos", sortOrder: 70 },
  { code: "12", label: "12 anos", sortOrder: 80 },
  { code: "14", label: "14 anos", sortOrder: 90 },
  { code: "16", label: "16 anos", sortOrder: 100 },
  { code: "20", label: "PP", sortOrder: 110 },
  { code: "21", label: "P", sortOrder: 120 },
  { code: "22", label: "M", sortOrder: 130 },
  { code: "23", label: "G", sortOrder: 140 },
  { code: "24", label: "GG", sortOrder: 150 },
  { code: "25", label: "XGG", sortOrder: 160 },
  { code: "26", label: "Unico", sortOrder: 170 },
  { code: "27", label: "Variado", sortOrder: 180 },
  { code: "28", label: "Combinei", sortOrder: 190 },
  { code: "36", label: "36", sortOrder: 200 },
  { code: "37", label: "37", sortOrder: 210 },
  { code: "38", label: "38", sortOrder: 220 },
  { code: "40", label: "40", sortOrder: 230 },
  { code: "42", label: "42", sortOrder: 240 },
  { code: "44", label: "44", sortOrder: 250 },
  { code: "46", label: "46", sortOrder: 260 },
  { code: "48", label: "48", sortOrder: 270 },
  { code: "50", label: "50", sortOrder: 280 },
  { code: "52", label: "52", sortOrder: 290 },
  { code: "54", label: "54", sortOrder: 300 },
  { code: "56", label: "56", sortOrder: 310 }
];

export const PEPPER_COLOR_REFERENCES: PepperReferenceItem[] = [
  { code: "01", label: "Preto", sortOrder: 10 },
  { code: "02", label: "Bege", sortOrder: 20 },
  { code: "03", label: "Vermelho", sortOrder: 30 },
  { code: "04", label: "Amarelo", sortOrder: 40 },
  { code: "05", label: "Rosa", sortOrder: 50 },
  { code: "06", label: "Verde", sortOrder: 60 },
  { code: "07", label: "Pink", sortOrder: 70 },
  { code: "08", label: "Rose", sortOrder: 80 },
  { code: "09", label: "Cinza", sortOrder: 90 },
  { code: "10", label: "Azul Royal", sortOrder: 100 },
  { code: "11", label: "Azul Marinho", sortOrder: 110 },
  { code: "12", label: "Verde Militar", sortOrder: 120 },
  { code: "13", label: "Esmeralda", sortOrder: 130 },
  { code: "14", label: "Vinho", sortOrder: 140 },
  { code: "15", label: "Grafite", sortOrder: 150 },
  { code: "16", label: "Branco", sortOrder: 160 },
  { code: "17", label: "Variadas", sortOrder: 170 },
  { code: "18", label: "Claro", sortOrder: 180 },
  { code: "19", label: "Escuro", sortOrder: 190 },
  { code: "20", label: "Combinei", sortOrder: 200 },
  { code: "21", label: "Laranja", sortOrder: 210 },
  { code: "22", label: "Azul", sortOrder: 220 },
  { code: "23", label: "Estampado", sortOrder: 230 },
  { code: "24", label: "Liso", sortOrder: 240 },
  { code: "25", label: "Alca fina", sortOrder: 250 },
  { code: "26", label: "Alca grossa", sortOrder: 260 },
  { code: "27", label: "Roxo", sortOrder: 270 },
  { code: "28", label: "Oncinha", sortOrder: 280 },
  { code: "29", label: "Marrom", sortOrder: 290 },
  { code: "30", label: "Verde Folha", sortOrder: 300 },
  { code: "31", label: "Acai", sortOrder: 310 },
  { code: "44", label: "Satin", sortOrder: 320 },
  { code: "52", label: "Salmao", sortOrder: 330 },
  { code: "54", label: "Fucsia", sortOrder: 340 },
  { code: "55", label: "Lilas", sortOrder: 350 },
  { code: "56", label: "Verde Azulado", sortOrder: 360 },
  { code: "57", label: "Verde Claro", sortOrder: 370 },
  { code: "58", label: "Telha", sortOrder: 380 },
  { code: "59", label: "Verde Abacate", sortOrder: 390 },
  { code: "60", label: "Azul Claro", sortOrder: 400 },
  { code: "61", label: "Rosa Choque", sortOrder: 410 },
  { code: "62", label: "Chumbo", sortOrder: 420 },
  { code: "63", label: "Rosa Claro", sortOrder: 430 },
  { code: "64", label: "Verde Agua", sortOrder: 440 },
  { code: "65", label: "Azul Turquesa", sortOrder: 450 },
  { code: "66", label: "Verde Musgo", sortOrder: 460 },
  { code: "67", label: "Verde Bandeira", sortOrder: 470 },
  { code: "68", label: "Verde Lima", sortOrder: 480 },
  { code: "69", label: "Amarelo Claro", sortOrder: 490 },
  { code: "70", label: "Violeta", sortOrder: 500 },
  { code: "71", label: "Dourado", sortOrder: 510 },
  { code: "72", label: "Creme", sortOrder: 520 },
  { code: "73", label: "Rosa Bebe", sortOrder: 530 },
  { code: "79", label: "Azul Bebe", sortOrder: 540 },
  { code: "82", label: "Mostarda", sortOrder: 550 },
  { code: "84", label: "Goiaba", sortOrder: 560 },
  { code: "86", label: "Magenta", sortOrder: 570 },
  { code: "87", label: "Cinza Azulado", sortOrder: 580 },
  { code: "88", label: "Azul Jeans", sortOrder: 590 },
  { code: "89", label: "Azul Bic", sortOrder: 600 },
  { code: "90", label: "Azul Violeta", sortOrder: 610 },
  { code: "91", label: "Areia", sortOrder: 620 },
  { code: "92", label: "Verde Tiffany", sortOrder: 630 },
  { code: "93", label: "Verde Menta", sortOrder: 640 }
];

export function buildPepperReferenceMap(items: PepperReferenceItem[]) {
  return Object.fromEntries(items.map((item) => [item.code, item.label] as const));
}
